#.travis.yml

language: node_js
node_js:
- "8.11.1"

branches:
  only:
  - master

before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli

script:
- ng build --prod

after_success:
- firebase deploy --token 1/DlxWvq_zV0eQAzVxUVMnYaYU4nwNGpLTtR3Md10sMCnMJDIB15zVbU6blxifxlCq


notifications:
  email:
    on_failure: change
    on_success: change
